# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.bin:$HOME/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="obraun"
ZSH_THEME="gnzh"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR=vim

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias ow="sudo lsof -i -P -n | grep LISTEN"
alias fw="sudo ufw status"

# Additional tools & plugins
# Setup scm breeze (git shortcuts)
[ -s "/home/ubuntu/.scm_breeze/scm_breeze.sh" ] && source "/home/ubuntu/.scm_breeze/scm_breeze.sh"
