#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    lua_shared_dict onetime 10m;
    sendfile        on;
    #tcp_nopush     on;
    #keepalive_timeout  0;
    keepalive_timeout  65;
    gzip  on;

    server {
        listen       80;
        server_name  _;
        lua_code_cache off;

        #charset koi8-r;
        #access_log  logs/host.access.log  main;

        root /usr/local/openresty/nginx/html;
        index index.html;
        error_page 400 401 403 404 500 503 /error.html;

        location ~* ^/(.*)$ {
            autoindex off;
            add_header Content-Type "text/plain";
            access_by_lua_block {
                local key = ngx.var.remote_addr .. ":" .. ngx.var.uri
                local dict = ngx.shared.onetime
                local visited = dict:get(key)
                if visited then
                    return ngx.exit(401)
                else
                    dict:set(key, true)
                end
            }

            # ... your normal config ...
            try_files $uri $uri/ =404;
        }
    }
}